gitGraph
  commit id: "init"
  branch develop
  checkout develop
  commit id: "ci base"
  branch feature/10-sliding-window
  commit id: "ventana"
  commit id: "pruebas"
  checkout develop
  merge feature/10-sliding-window
  branch feature/13-revert-war
  commit id: "detector"
  checkout develop
  merge feature/13-revert-war
  branch release/1.0
  commit id: "version 1.0.0"
  checkout main
  merge release/1.0 tag: "v1.0.0"
  checkout develop
  merge release/1.0
  checkout main
  branch hotfix/1.0.1
  commit id: "fix reconexion"
  checkout main
  merge hotfix/1.0.1 tag: "v1.0.1"
  checkout develop
  merge hotfix/1.0.1
